# First run the following command. Once it is running. Cancel it.
# docker compose up --build
# Then run...
# docker compose up -d   or restart the solution in docker desktop
services:
  mariadb:
    image: mariadb:10.11.10-jammy
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuser1234
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      # PMA_USER: pmauser | use the mysql user and pass
      # PMA_PASSWORD: pma1234
    ports:
      - "8080:80"
    depends_on:
      - mariadb
