services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 6060:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp-networks
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows WordPress to reach Express server on your local machine

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wp-networks

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5
    restart: always
    ports:
      - "3406:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - wp-networks

networks:
  wp-networks:
    driver: bridge

volumes:
  wordpress:
  db:
